package enitiy;
// Generated Mar 24, 2018 11:40:24 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="CATEGORY"
    ,schema="SHOP"
    , uniqueConstraints = @UniqueConstraint(columnNames="CATEGORY_NAME") 
)
public class Category  implements java.io.Serializable {


     private BigDecimal categoryId;
     private String categoryName;

    public Category() {
    }

	
    public Category(BigDecimal categoryId) {
        this.categoryId = categoryId;
    }
    public Category(BigDecimal categoryId, String categoryName) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
    }
   
     @Id 

    
    @Column(name="CATEGORY_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(BigDecimal categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="CATEGORY_NAME", unique=true, length=100)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }




}


