package enitiy;
// Generated Mar 24, 2018 11:40:24 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="PRODUCTS"
    ,schema="SHOP"
)
public class Products  implements java.io.Serializable {


     private BigDecimal productId;
     private String productName;
     private String productDescription;
     private BigDecimal productQuanitity;
     private String productImage;
     private BigDecimal productSalary;
     private BigDecimal categoryId;

    public Products() {
    }

	
    public Products(BigDecimal productId) {
        this.productId = productId;
    }
    public Products(BigDecimal productId, String productName, String productDescription, BigDecimal productQuanitity, String productImage, BigDecimal productSalary, BigDecimal categoryId) {
       this.productId = productId;
       this.productName = productName;
       this.productDescription = productDescription;
       this.productQuanitity = productQuanitity;
       this.productImage = productImage;
       this.productSalary = productSalary;
       this.categoryId = categoryId;
    }
   
     @Id 

    @GeneratedValue(strategy=SEQUENCE)
    @Column(name="PRODUCT_ID", unique=true, nullable=false, precision=22, scale=1)
    public BigDecimal getProductId() {
        return this.productId;
    }
    
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

    
    @Column(name="PRODUCT_NAME", length=200)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="PRODUCT_DESCRIPTION", length=500)
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    
    @Column(name="PRODUCT_QUANITITY", precision=22, scale=0)
    public BigDecimal getProductQuanitity() {
        return this.productQuanitity;
    }
    
    public void setProductQuanitity(BigDecimal productQuanitity) {
        this.productQuanitity = productQuanitity;
    }

    
    @Column(name="PRODUCT_IMAGE", length=200)
    public String getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    
    @Column(name="PRODUCT_SALARY", precision=22, scale=0)
    public BigDecimal getProductSalary() {
        return this.productSalary;
    }
    
    public void setProductSalary(BigDecimal productSalary) {
        this.productSalary = productSalary;
    }

    //@ManyToOne
   // @JoinColumn(name="CATEGORY_ID")
    @Column(name="CATEGORY_ID", precision=22, scale=0)
    public BigDecimal getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(BigDecimal categoryId) {
        this.categoryId = categoryId;
    }




}


