package enitiy;
// Generated Mar 24, 2018 11:40:24 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="USERS"
    ,schema="SHOP"
    , uniqueConstraints = @UniqueConstraint(columnNames="USER_EMAIL") 
)
public class Users  implements java.io.Serializable {


     private BigDecimal userId;
     private String userName;
     private Date birthdate;
     private String userEmail;
     private String userPassword;
     private String userJob;
     private BigDecimal creditLimit;
     private String userAddress;
     private BigDecimal admin;

    public Users() {
    }

	
    public Users(BigDecimal userId, String userEmail) {
        this.userId = userId;
        this.userEmail = userEmail;
    }
    public Users(BigDecimal userId, String userName, Date birthdate, String userEmail, String userPassword, String userJob, BigDecimal creditLimit, String userAddress, BigDecimal admin) {
       this.userId = userId;
       this.userName = userName;
       this.birthdate = birthdate;
       this.userEmail = userEmail;
       this.userPassword = userPassword;
       this.userJob = userJob;
       this.creditLimit = creditLimit;
       this.userAddress = userAddress;
       this.admin = admin;
    }
   
     @Id 

    
    @Column(name="USER_ID", unique=true, nullable=false, precision=22, scale=0)
         @GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
    @SequenceGenerator(name = "id_Sequence", sequenceName = "USERS_SEQ")
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    
    @Column(name="USER_NAME", length=100)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BIRTHDATE", length=7)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="USER_EMAIL", unique=true, nullable=false, length=100)
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    
    @Column(name="USER_PASSWORD", length=100)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    
    @Column(name="USER_JOB", length=50)
    public String getUserJob() {
        return this.userJob;
    }
    
    public void setUserJob(String userJob) {
        this.userJob = userJob;
    }

    
    @Column(name="CREDIT_LIMIT", precision=22, scale=0)
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="USER_ADDRESS", length=100)
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    
    @Column(name="ADMIN", precision=22, scale=0)
    public BigDecimal getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(BigDecimal admin) {
        this.admin = admin;
    }




}


